dist: xenial
group: travis_latest

branches:
  only:
  - master

language: python

matrix:
  include:
  - python: "3.7"
    env: TOXENV=flake8
  - python: "3.8"
    env: TOXENV=py38
  - python: "3.7"
    env: TOXENV=py37
  - python: "3.6"
    env: TOXENV=py36
  - python: "3.5"
    env: TOXENV=py35
  - python: "2.7"
    env: TOXENV=py27

install:
  - pip install --upgrade tox

script:
  - tox
